name: CI CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  IMAGE_NAME: hello-k8s

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}    # OR use access key id/secret via secrets
          role-session-name: github-actions

      - name: Login to ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, push image
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
        env:
          DOCKER_BUILDKIT: 1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy to Kubernetes
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          # replace image in deployment manifest and apply
          kubectl set image -n default deployment/hello-deploy hello=$IMAGE_URI --record || true
          kubectl apply -f k8s/base

